#!/bin/bash
#PBS -l select=1:ncpus=4:mem=64gb
#PBS -l walltime=240:00:00
#PBS -j oe
#PBS -q fthpc
#PBS -N xcompress
#PBS -M ptriant@g.clemson.edu
#PBS -m ae
#PBS -J 1-10

module load gcc/4.8.1
module load mpich
module load python/3.4

cd $PBS_O_WORKDIR

tol=1E-${PBS_ARRAY_INDEX}
compressor=zfp-0.5.4
num_iter=100
simple_dll=./compressors/$compressor/examples/simple.dll
file=./results/$compressor/$tol/$num_iter.txt

python h5_parser_compressor.py $tol $num_iter $simple_dll > $file
